# Generated by Django 5.0.1 on 2024-06-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XBOX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
