# Generated by Django 5.0.1 on 2024-06-08 03:16

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XBOX', '0003_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
